conda-forge/docker-images

README.md

DOC: Fix typo

---

linux-anvil/Dockerfile

This improves cache cleaning with `conda` so as to reduce image size. Also, it fixes a warning that `conda` was generating at one point.

Clean conda cache

---

linux-anvil/Dockerfile

Adds a few comments and cleans up some old ones.
* Remove some lingering commented code from Obvious-CI.
* Explain the entrypoint scripts.
* Note the entrypoint adds conda and the devtoolset compiler to the path.

Refresh comments

---

linux-anvil/Dockerfile

This is an intermediate step to build packages as a non-root user.
Current recipes should still work with this image without changes.

Create non-root user and install sudo and gosu

---

LICENSE

Fixes https://github.com/conda-forge/docker-images/issues/40
cc @conda-forge/core

Switch to BSD 3-Clause license

---

scripts/run_commands

So that the installation is not upgraded to python 3.7

Stop python downgrade

---

linux-anvil-comp7/Dockerfile

Related to #82
Remove gcc7 channel from the comp7

Cache the right stuff

---

.circleci/test_docker_container.sh
.travis.yml

Fix testing

---

scripts/run_commands

Use Miniconda 4.6.14

---

linux-anvil-aarch64/Dockerfile
linux-anvil-comp7/Dockerfile
linux-anvil-cuda/Dockerfile
linux-anvil-ppc64le/Dockerfile
scripts/run_commands

Drops `patch` from the system and installs it with Conda instead.
Checklist

Use our patch

---

.travis.yml

Upgrade the version of qemu that we are using.  This should give better compatiblity.

Use qemu 4.0.0 for emulation

---

linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile
linux-anvil-cuda/Dockerfile
linux-anvil-ppc64le/Dockerfile

Update compiler package caching

---

linux-anvil-ppc64le/Dockerfile

We have new package on conda-forge.
(These were built manually as travis-ci times out.)

Use conda-forge packages

---

linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile
linux-anvil-cuda/Dockerfile

Use conda-forge

---

linux-anvil-aarch64/Dockerfile
scripts/run_commands

cc @hmaarrfk, @hadim, @jjhelmus

Bye bye c4aarch64

---

linux-anvil-cuda/Dockerfile

See discussion [here](https://github.com/conda-forge/cupy-feedstock/pull/59#issuecomment-630279115). @isuruf

add content of ldconfig to ld.so.conf.d before $CUDA_HOME/compat

---

.travis.yml
linux-anvil-comp7/Dockerfile

install the qemu user binary on linux-64 for emulation

---

linux-anvil-aarch64/Dockerfile
linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile
linux-anvil-cuda/Dockerfile
linux-anvil-ppc64le-cuda/Dockerfile
linux-anvil-ppc64le/Dockerfile

Replace link for busting the cache

---

.travis.yml
scripts/deploy

BUG deploy can only be one line

---

.github/workflows/ci.yaml
README.md

BUG fix status badge

---

.github/workflows/ci.yaml
linux-anvil-cuda/Dockerfile

Add CUDA 11.1

---

.github/workflows/ci.yaml

Add linux-anvil-cos7-cuda images

---

.circleci/run_docker_build.sh
.github/workflows/ci.yaml
miniforge3/Dockerfile

add mambaforge

---

.github/workflows/ci.yaml

update cuda 11.2 to 11.2.1

---

.github/workflows/ci.yaml

xref: https://github.com/conda-forge/cudatoolkit-feedstock/pull/57#issuecomment-804063842
cc @mike-wendt @kkraus14 @jaimergp @leofang

Update CUDA 11.2 image to 11.2.2

---

linux-anvil-aarch64/Dockerfile
linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile
linux-anvil-cuda/Dockerfile
linux-anvil-ppc64le-cuda/Dockerfile
linux-anvil-ppc64le/Dockerfile

Replace `randomtext.me` by `loripsum.net` as it seems to be down for a long time

Replace randomtext.me by loripsum.net

---

download-qemu-static.sh
linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile

Add s390x qemu

---

download-qemu-static.sh

Newer releases of qemu have greater compatibility and performance

Update qemu-static to 6.1.0

---

scripts/run_commands

update to miniforge 4.11.0

---

.github/workflows/ci.yaml
README.md
linux-anvil-aarch64-cuda/Dockerfile
linux-anvil-aarch64/Dockerfile
linux-anvil-comp7/Dockerfile
linux-anvil-cos7-x86_64/Dockerfile
linux-anvil-cuda/Dockerfile
linux-anvil-ppc64le-cuda/Dockerfile
linux-anvil-ppc64le/Dockerfile
scripts/setup_openjdk

Allow Linux distro name to be specified with `DISTRO_NAME` ( needed for PR https://github.com/conda-forge/docker-images/pull/214 ). Also rename `CENTOS_VER` to `DISTRO_VER`.

Specify distro name & version

---

.github/workflows/keep-alive.yaml

add keep alive workflow

---

.github/workflows/keep-alive.yaml

Checklist
Comes from https://github.com/conda-forge/docker-images/pull/219#discussion_r987653446

Pin keep alive

---

scripts/run_commands

Checklist
Fix conflict errors with 4.11.

use conda 4.14

---

scripts/run_commands

xref: https://github.com/conda-forge/miniforge/pull/361
xref: https://github.com/conda-forge/docker-images/pull/222
cc @hmaarrfk @jaimergp

Update to Mambaforge 22.9.0-0

---

.github/workflows/ci.yaml

Add CUDA 11.8 images 

---

download-qemu-static.sh

Upgrade qemu to 7.1.0

---

download-qemu-static.sh

Fixes https://github.com/conda-forge/docker-images/issues/226
cc @conda-forge/core

Update QEMU to 7.2.0

---

scripts/run_commands

give sudo permission to copy the cuda headers and libraries for cross compilation

---

scripts/run_commands

Checklist
See https://github.com/conda-forge/staged-recipes/issues/24113

Remove boa

---

.github/workflows/ci.yaml
Dockerfile_README.md
scripts/gen_readme

ENH generate the readmes

---

download-qemu-static.sh

QEMU 8.2.4

---

.github/CODEOWNERS

This should reflect who is reviewing and merging PRs here.

Make @conda-forge/core CODEOWNERS

---

.circleci/test_docker_container.sh
scripts/run_commands

Part of https://github.com/conda-forge/conda-smithy/pull/2075, but for Linux

Install `micromamba` to `/opt/conda/condabin`

---

linux-anvil-cuda/Dockerfile
linux-anvil/Dockerfile

fix: loripsum API is broken

---

linux-anvil-cuda/Dockerfile
linux-anvil/Dockerfile

install diffutils in the docker images

---

.github/workflows/ci.yaml

Replace deprecated keepalive action with `gh api` call

---

.github/workflows/ci.yaml

Fix comment on pinned action
