obvious-ci/Dockerfile, obvious-ci/entrypoint, obvious-ci/entrypoint_source
@pelson, as [discussed]( https://github.com/conda-forge/conda-forge.github.io/pull/121/files#diff-e482962a4824eb0dcd693fea95aca49eR116 ) after the general meeting on the 2016-04-29, I am adding this PR to add the `obvious-ci` docker image here. This is being removed it from the [Obvious-CI repo]( https://github.com/pelson/Obvious-CI ) in this PR ( https://github.com/pelson/Obvious-CI/pull/65 ). Also, will setup a Docker Hub autobuild in a moment. Already tried building this locally from this repo here and it works fine.
=> Add obvious-ci docker source

linux-anvil/Dockerfile
Fixes https://github.com/conda-forge/docker-images/issues/7
Update the maintainer of `linux-anvil` to be the organization.
=> Update linux-anvil maintainer

README.md, circle.yml
Configure the repo so that it can perform CI with CircleCI. This will let us test the builds of our images quickly and will avoid having to build them by hand locally. Hopefully with this change we can have a better idea of whether a proposed change is working without needing to spend cycles building it locally. To start of the CI, this just tries to get the image built. In the future, this could be used to test image(s) built to make sure they behave ok.
=> Configure CircleCI

linux-anvil-mirror/Dockerfile
Partially resolves https://github.com/conda-forge/docker-images/issues/14
This adds a `Dockerfile` that merely pulls the [image]( https://quay.io/repository/condaforge/linux-anvil ) we are building on [quay.io]( https://quay.io/ ). The purpose of doing this is we could change our Docker Hub build to use this instead of building the image from scratch. Thus we will not need to go through and change our `FROM` commands, but we can actually build our image again. This is increasingly important as we are needing to make changes to it.
Additionally, I have enabled a webhook on the Docker Hub side and configured quay.io to post using that webhook after pushing an image. I just tested this system and it appears to work. So, when we merge something here it will be rebuilt on quay.io and once …
=> Add a Dockerfile to mirror quay.io

linux-anvil/Dockerfile
This adds a step that always busts the cache. Based on a [workaround]( https://github.com/docker/docker/pull/10682#issuecomment-178810479 ) offered in-place of the unaccepted `NOCACHE` command. The purpose of this step is to ensure that we are not re-using cached downloads. We accomplish this by `ADD`ing a file that we download from a URL that always changes. Namely we add a file that contains the current time. As a result, we will have a different hash for this layer each time and will need to generate every subsequent layer from scratch.
=> Bust the cache in linux-anvil

linux-anvil/Dockerfile
We are getting a `NOKEY` warning during the linux-anvil build when running `yum`. This should ensure the key is imported so that this warning is not issued.
The warning this avoids is shown below and can be seen in this [log]( https://circleci.com/gh/conda-forge/docker-images/3 ). Also, it can be seen in [quay]( https://quay.io/repository/condaforge/linux-anvil/build/cf7d2de8-41a3-4557-a141-b1b1e4b7dc19 ) too.
```
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID c105b9de: NOKEY
```
=> Fix NOKEY warning in linux-anvil

linux-anvil/Dockerfile
Instead of `yum` installing `git`, install our much newer (and nicer 😄) copy of `git` built right here at `conda-forge` in the image. Should add that installing `git` with `yum` pulled in stuff like `perl` which we would rather not have around as we have our own `perl` that we would prefer.
=> Use `git` from `conda-forge` in `linux-anvil`

linux-anvil/Dockerfile
Currently, we do not add the `conda-forge` channel in the docker image. While this initially made sense given the history of this docker image (as it [precedes]( https://github.com/pelson/Obvious-CI/blob/d82cabc1f80a0151b914d3ebb498043ace169562/obvious-ci.docker/linux64_obvci/Dockerfile ) conda-forge), it has long since migrated to conda-forge and has been upgraded accordingly. While this itself doesn't justify adding the channel, it does show that there should not be any significant blockers to doing so.
That all being said, there are some good reasons for including the `conda-forge` channel at this stage. Right now a sizable amount of time in each CircleCI build is spent updating from `defaults` packages to `conda-forge` packages. This is being done in every CircleCI build no matter …
=> Add conda-forge channel

linux-anvil/entrypoint
Previously the `PS1` prompt was set correctly by `bash` when the container started.
However, now `conda` mucks with `PS1` before `bash` starts in activation. So `bash` won't change the prompt afterwards. Further `conda` deactivation will hang.
This sets the prompt before `conda` activates so that there is a prompt and `conda` deactivation works. This is primarily of value for offline use.
Tested for local use interactively. Also tested building `pycrypto` with the Docker build script using it. Both worked fine.
=> Fix prompt

linux-anvil/Dockerfile
Update to `tini` version `0.10.0` so that the license is included. This ensures we are compliant with the terms of the MIT license that `tini` is under.
**Changelog:**
```
- New `-l` option to show license and exit.
```
cc @tylere
=> Update to `tini` version `0.10.0`

linux-anvil/Dockerfile
This picks a particular version of Miniconda to install (still the most recent one available) and installs it. Also, it verifies that its checksum matches what we expect it too. Not that we have any reason to think these wouldn't match. Still it is good practice to be using checksums to verify things that we have downloaded.
We need to pick a particular Miniconda version so that we can be sure about the checksum we are getting. If we were downloading latest, the checksum would change when there is a new Miniconda release. This shouldn't be a problem when we download a specific version.
In the future, we will need to explicitly update our Miniconda installs to new versions as needed. However, in practice, we may not need to do this very often as we upgrade everything in the Docker build …
=> Validate Miniconda download with checksum

linux-anvil/Dockerfile
This proposes we drop the system `gcc`. As we already include the devtoolset compiler, there is really no need for this other compiler to also be installed. After all the system `gcc` is not even used. Dropping the system `gcc` would result in a ~5% size reduction in the final image. Have tested some simple C and C++ programs to verify this doesn't have any effect.
=> Drop system `gcc` (have devtoolset already)

linux-anvil/Dockerfile
Fixes the download URL for Miniconda as has been done for Travis and AppVeyor.
xref: https://github.com/conda-forge/conda-smithy/pull/347
xref: https://github.com/conda-forge/conda-smithy/pull/348
=> Fix Miniconda download

.circle_support/checkout_merge_commit.sh, circle.yml
Unlike other CIs, CircleCI does not test the merge commit of a PR with its base branch. Instead it tests the PR's head commit. The problem with this is the PR's status could differ when it is merged with the base branch. For instance, if one needs changes in the base branch to get their PR to pass, they must rebase/merge to get them into the history the PR. This normally isn't a problem, but sometimes things do go wrong when doing this merge/rebase, which adds a new unneeded difficulty. Alternatively, a passing PR could turn out to fail when merged into the base branch because some new content in the base branch was not tested against in the PR.
To solve these issues, we checkout the merge ref for a PR (if it is a PR) from GitHub. However, it should be noted that the merge ref can be …
=> Test CircleCI PR merge commits

linux-anvil/Dockerfile
It appears that timeapi.org has been taken offline and the domain is up for grabs. To still ensure the cache is busted at the beginning of the Docker build, this switches to the USNO's time service to get the time since the last epoch. This should allow us to still bust the cache and save the time when the image was built.
=> Switch to the USNO's time service

linux-anvil/Dockerfile
Drops the last vestige of Obvious-CI from the docker-image and handles this install step directly. Thus removing the need for this Obvious-CI script.
=> Install conda build and deployment tools directly

linux-anvil/Dockerfile
Instead of downloading the pre-built binary for `tini`. Install our own `conda-forge` package for `tini`, which we build from source.
=> Install and use conda-forge's tini

linux-anvil/Dockerfile
Now that we support `conda` 4.3 in `conda-forge` start with the newest Miniconda (4.3.21), which includes `conda` 4.3.21 and uses `python` 3.6.
=> Use Miniconda 4.3.21

linux-anvil/entrypoint
Touch up to PR ( https://github.com/conda-forge/docker-images/pull/36 ).
As we were only using `chown` and not `chown -R` with `/home/conda/.condarc`, the user changed to `conda`, but the group remained `root`. This fixes that issue by forcing the user and group to be changed to `conda` explicitly for `/home/conda/.condarc`.
=> Ensure `conda` group owns `/home/conda/.condarc`

linux-anvil/entrypoint
Touch up to PR ( https://github.com/conda-forge/docker-images/pull/36 ).
Instead of dropping into `/`, it makes more sense to drop into `/home/conda`. As we use absolute paths throughout, this is largely a cosmetic touch. However it would help if the current working directory is a place that allows us to create things without issues.
=> Switch to the `conda` user's home directory

linux-anvil/entrypoint
Follow-up to PR ( https://github.com/conda-forge/docker-images/pull/36 ).
Fixes a few issues that crop up when `/home/conda` already exists (normally due to the mount location being with `/home/conda`). Namely make sure the `conda` user owns their home directory and includes the files from `/etc/skel`. Also make sure `/opt/conda` belongs to the `conda` group.
=> Fix user creation when user's home directory already exists

linux-anvil/Dockerfile
Separates out the `tini` install from the other development tools installed for building recipes and uploading packages. Should make it a little more obvious how things relate in the Docker image.
=> Break up `tini` install

linux-anvil/Dockerfile, linux-anvil/entrypoint
Switches over to our `gosu` package instead of downloading a prebuilt binary. Since it was built in our Docker image, we know it is compatible with CentOS 6. Also as we built this copy of `gosu` ourselves, we are able to more easily include things like the license file.
=> Use our gosu

linux-anvil/Dockerfile
Appears that USNO's time server redirects to `https`, but their certificates are invalid for some reason. Probably a consequence of their recent move to `https`. Would expect them to fix this in the future. For now, switch to a new time server to bust the cache. This provides the output in JSON with a few formats as opposed to a simple string, but is otherwise just text. Should work for our needs.
=> Use new time server to bust cache

scripts/run_commands
There are a few holdovers in `scripts/run_commands` from when it used to be part of the `Dockerfile`. As it is now a bash script, these things can be cleaned up and streamlined a bit. Plus we could use a bit more visibility into the script while it runs on CI by echoing commands to make it easier to see when problems show up.
=> Improve debugging in `scripts/run_commands`

linux-anvil/entrypoint_source, linux-anvil2/entrypoint_source, scripts/run_commands
Make use of Miniconda 4.5.4. Also update the activation steps to reflect the preferred strategy after conda 4.4.0+.
=> Use Miniconda 4.5.4

scripts/run_commands
As this is a file downloaded by `root`, the system will ask us to confirm our decision to remove the file. Since we are running in batch, it simply assumes the answer is no and proceeds. As a result, a copy of `miniconda.sh` (weighing in at about 34MB) is getting packaged in our Docker image increasing the image size.
To fix this, start using `rm -f` to forcibly remove `miniconda.sh`. This way when Docker goes to commit this layer, `miniconda.sh` won't be present and so will not be included. Should help improve image size and cutdown on clutter.
=> Use force when removing `miniconda.sh`

linux-anvil-comp7/Dockerfile
Make sure the new compiler packages are downloaded and cached to make it easier to install quickly at build time.
cc @mariusvniekerk
=> Download and cache new compiler packages

linux-anvil-comp7/Dockerfile
All of these are either conda-forge packages that we should be using and/or are using or there are CDTs we should be using for these. Given this, go ahead and drop these X11 packages from the new compiler Docker image. Admittedly this is a breaking change for some packages, but one that we are already adapting in many places.
=> Drop X11 reqs from new compiler Docker image

linux-anvil-aarch64/Dockerfile, linux-anvil-comp7/Dockerfile, linux-anvil-ppc64le/Dockerfile, linux-anvil/Dockerfile
This fixes the issues where much of the locale information is stripped out of the container that we use to build stuff.
This fixes a lot of the _"Failed to set locale, defaulting to C"_ style message that appear during certain builds
=> Fixed missing locale pieces for aarch64 and ppc64le

linux-anvil-comp7/Dockerfile
We were installing some of these packages from conda-forge while they were included in our channel (as part of a workaround during the compiler migration). However we no longer include them in our channel. So this updates this install command to grab them from defaults where they are available.
=> Fix compiler install

.travis.yml
Go ahead and specify the Docker image's tag as well. This should simplify the build scripts a bit and make things more extensible for use cases that would like to specify the tag.
=> Specify Docker image's tag as well

.travis.yml, linux-anvil-cuda/Dockerfile, linux-anvil-cuda/entrypoint_source
Have been using this to build some GPU packages for work. Am placing it up here as a draft PR to solicit feedback and start the discussion towards building a community standard. Please share your thoughts.
**Summary:** This creates a Docker image that inherits from the [NVIDIA CUDA Docker images]( https://hub.docker.com/r/nvidia/cuda/ ), which include CUDA and NVCC. This largely borrows from the [`condaforge/linux-anvil-comp7` image]( https://github.com/conda-forge/docker-images/tree/master/linux-anvil-comp7 ) with minor modifications (hopefully clear in the commit history). The goal is to provide a base image for performing Linux GPU builds in.
cc @kkraus14 @mike-wendt @mrocklin @datametrician @msarahan @seibert @jjhelmus @soumith (feel free to include others I may have missed)
=> Add CUDA build image

linux-anvil-comp7/Dockerfile, linux-anvil-cuda/Dockerfile
Fixes https://github.com/conda-forge/docker-images/issues/78
As we are using `make` from `conda-forge` increasingly in recipes when doing a build (partially due to the aarch64/ppc64le migration and partially due to our new best practices), go ahead and drop them from our containers. This will also ensure that recipes add this requirement before going through the aarch64/ppc64le migration, which should help make that migration a bit smoother.
cc @hmaarrfk @conda-forge/core
Checklist
=> Drop `make` from Docker images

linux-anvil-aarch64/Dockerfile, linux-anvil-comp7/Dockerfile, linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le/Dockerfile
Applies the same changes we have in the ARM and POWER images to our other images to ensure the locales are working correctly.
Note: This also comes up in [this SO answer]( https://unix.stackexchange.com/a/140517 ).
Checklist
=> Ensure locales work

linux-anvil-cuda/Dockerfile
It appears that Docker will forget the build argument during the build if it was used in `FROM`. Redeclaring the build argument after `FROM` seems to work. Also this allows us to inject it into an environment variable for easier use later on.
ref: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
=> Redeclare `CUDA_VER` build argument

.travis.yml, docker_daemon_config.json
Fixes https://github.com/conda-forge/docker-images/issues/82
This enables [Docker's experimental features]( https://github.com/docker/docker-ce/blob/554e31a7e6544d17ef74d5656c0e6d1af590fbd0/components/cli/experimental/README.md#use-docker-experimental ) on Travis CI, which are needed to run `docker build` with [the `--squash` flag]( https://github.com/docker/docker-ce/blob/554e31a7e6544d17ef74d5656c0e6d1af590fbd0/components/cli/docs/reference/commandline/build.md#squash-an-images-layers---squash-experimental ). When using this flag with `docker build`, all layers are squashed together into one layer at the end. This history itself is retained, but none of the previous layers contain anything addition. Though the base image (used in `FROM`) is retained in the history with its original …
=> Use `docker build --squash...`

.circleci/config.yml
This image is newer and actively used (unlike `condaforge/linux-anvil`). So switch the CircleCI tests to use this image instead.
xref: https://github.com/conda-forge/docker-images/issues/101
=> Test `condaforge/linux-anvil-comp7` on CircleCI

.travis.yml
@mariusvniekerk in https://github.com/conda-forge/conda-build-feedstock/pull/101#issuecomment-510133675 :
> I'm not entirely sure what the build errors are on the emulated platforms. It suggests that there may be some issues with how qemu operates since we moved to 4.0.0-5 Should we roll that back to the last good 3.x release?
@mbargull in https://github.com/conda-forge/conda-build-feedstock/pull/101#issuecomment-510181473 :
> Looks like @mariusvniekerk is spot-on:
> ```sh
> >>> docker run --rm -it --entrypoint='' mbargull/condaforge-linux-anvil-aarch64:qemu-3.1.0-3 /opt/conda> /bin/python -c 'import os;os.listxattr(".");print("all good")'
> all good
> >>> docker run --rm -it --entrypoint='' mbargull/condaforge-linux-anvil-aarch64:qemu-4.0.0-5 /opt/conda> /bin/python -c 'import …
```
=> Use qemu 3.1.0-3

.circleci/run_docker_build.sh, .circleci/test_docker_container.sh, linux-anvil-aarch64/Dockerfile, linux-anvil-comp7/Dockerfile, linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le/Dockerfile, scripts/run_commands, scripts/yum_clean_all
Do we really need the changes from gh-83 and gh-97?
It seems like https://github.com/CentOS/sig-cloud-instance-images/issues/71 is a resolved issue and the locale is working, isn't it?
I'd rather like us to test whether the locale is working and only apply fixes if it really is not.
I couldn't find a reference to a recent issue in gh-83. @mariusvniekerk, @hmaarrfk, can you point me to failing cases such that we can incorporate them in the tests?
Also, @mariusvniekerk, gh-83 has been for `aarch64` only. The only significant difference to `ppc64le` I could find is that `aarch64` does not have https://github.com/CentOS/sig-cloud-instance-build/commit/2892c17fa8a520e58c3f42cd56587863fe675670#diff-574fa022ad7d0be565da139e942a15cbR92 , i.e., it has `override_install_langs=en_US.UTF-8` in …
=>  Test for working en_US.UTF-8 locale 

.travis.yml, linux-anvil-armv7l/Dockerfile, linux-anvil-armv7l/entrypoint_source, scripts/run_commands
Add a Docker container for building linux-armv7l conda package.  Similar to `aarch64` the initial set of packages come from the `c4armv7l` channel on Anaconda.org which were build from the https://github.com/jjhelmus/conda4armv7l/ repository.
=> Add an armv7l container

.travis.yml
Includes a Docker image for building against CUDA 10.1.
Checklist
=> Add CUDA 10.1 image

linux-anvil-cuda/Dockerfile
Previously we were pulling the `entrypoint_source` from the `linux-anvil-comp7` directory. However we should have been pulling this from the `linux-anvil-cuda` directory. Hence we fix it accordingly in this PR.
Checklist
=> Use the CUDA image's `entrypoint_source`

linux-anvil-cuda/entrypoint_source
To ensure that the CUDA binaries are on the `PATH`, add them to the `PATH`. As we [overwrite the `PATH`]( https://github.com/conda-forge/docker-images/blob/6152d61e4afdc63816b4865a72bf17fbb9ced17c/scripts/entrypoint#L14 ) before this point, we cannot add the binaries to the `PATH` earlier (like in the Docker image) as they will be overwritten. In fact the NVIDIA image already adds the binaries to the `PATH`, but we already don't find them due to this overwriting. So add the CUDA binaries in the `entrypoint_source` script. This should ensure they are visible to the user and `conda-build` after starting up the container.
=> Add `CUDA_HOME` to the `PATH`

.travis.yml, linux-anvil-cuda/Dockerfile
This enables builds of the `condaforge/linux-anvil-cuda` for CUDA 10.2. Though this still needs `cudatoolkit` for CUDA 10.2.
=> Add linux-anvil-cuda docker image for CUDA 10.2

linux-anvil-cuda/Dockerfile
Checklist
This PR adds symlinks to CUBLAS headers in `$CUDA_HOME/include` for CUDA >=10.1.
I had an error with `#include "cublas_v2.h"` for builds of CUDA 10.1 and 10.2, but 9.2 and 10.0 work fine. The paths for CUBLAS changed in 10.1 ([described here](https://forums.developer.nvidia.com/t/cublas-for-10-1-is-missing/71015/2)). 
Some feedstocks have used workarounds for this, like cupy: https://github.com/conda-forge/cupy-feedstock/blob/04418f960647c9f04ffe30c45b716711474a08bb/recipe/meta.yaml#L30-L35
I was not able to build this PR locally. I got this error:
```
Step 11/22 : COPY scripts/yum_clean_all /opt/docker/bin
COPY failed: stat /var/lib/docker/tmp/docker-builder729234824/scripts/yum_clean_all: no such file or directory
```
=> Add step to symlink CUDA headers moved in CUDA 10.1.

linux-anvil-cuda/Dockerfile
Following [discussion](https://github.com/conda-forge/pyarrow-feedstock/pull/101#discussion_r416907727) in https://github.com/conda-forge/pyarrow-feedstock/pull/101, this is a best effort to fix things - I don't claim to understand the subject in depth, just trying to hack things together.
First off, I didn't want to use a `.deb` on centos, so I went with the `.rpm`'s from [upstream](https://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64/). Playing around in a `nvidia/cuda:9.2-devel-centos6` container, there's only a stub library:
```
[root@f2a51f1cbd4e /]# find /usr/ -name 'libcuda.so*'
/usr/local/cuda-9.2/targets/x86_64-linux/lib/stubs/libcuda.so
[root@56ddd2cd52b0 /]# ls -la /usr/local/cuda-9.2/targets/x86_64-linux/lib/stubs/libcuda.so
-rwxr-xr-x 1 root root 43192 Jun 13 …
```
=> fix missing libcuda.so on 9.2; adapt LD_LIBRARY_PATH

linux-anvil-cuda/Dockerfile
@isuruf
I'm sorry, I managed to confuse myself last night in #135 - the path added to ldconfig is not correct (it's  `/usr/local/cuda-$CUDA_VER/compat` == `$CUDA_HOME/compat` instead of  `$CUDA_HOME/compat-$CUDA_VER`).
The confirmation is here:
```
xxx@yyy:~$ sudo docker run --rm -it condaforge/linux-anvil-cuda:10.2 bash
[conda@750aa8f98caf ~]$ find /usr/ -name 'libcuda.so*'
/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-10.2/compat/libcuda.so
/usr/local/cuda-10.2/compat/libcuda.so.1
/usr/local/cuda-10.2/compat/libcuda.so.440.64.00
```
Please merge this at your earliest convenience.
=> fix wrong ldconfig path from #135

linux-anvil-cuda/Dockerfile
As discussed [here](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/93#discussion_r426364828). Alternative to #138.
Closes #138.
=> add /usr/local/cuda-10.0/compat to ldconfig for cuda 9.2

.travis.yml, linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile, linux-anvil-ppc64le-cuda/entrypoint_source
This adds a Docker image that is an amalgamation of the CUDA Docker image and the ppc64le images to enable building ppc64le packages that have CUDA portions enabled as well.
cc @jayfurmanek
Checklist
=> Add Docker image for ppc64le and CUDA

scripts/entrypoint
While working on feedstocks ourside of the conda-forge organization, I sometimes notice that some packages are taken from the conda-forge channel while the channel configuration lists only `nsls2forge` and `defaults`, so the channels selection is not respected.
This update may be useful for users of the conda-forge infrastructure who build packages based on the `defaults` and other non-conda-forge channels (e.g., https://github.com/nsls-ii-forge).
The proposed approach was tested on a custom Docker image based on https://github.com/nsls-ii-forge/utils/blob/master/nsls2forge-docker/Dockerfile / https://hub.docker.com/repository/docker/nsls2/nsls2forge applied to the following feedstock: https://github.com/nsls-ii-forge/hkl-feedstock/blob/master/recipe/conda_build_config.yaml. I'd …
=> Avoid shadowing of channels from global .condarc

.travis.yml, README.md
I am enabling pushes to quay as images are built. This way if docker hub starts rate limiting our CI jobs, we can move to quay instead.
=> ENH push to quay too

linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile
With CUDA 10.1, the `libcublas` package is broken by running `yum update`. So simply disable updates related to the `cuda` `yum` repo to avoid this breakage.
cc @leofang
xref: https://github.com/conda-forge/cupy-feedstock/pull/70
xref: https://github.com/rapidsai/gpuci-build-environment/pull/123
=> Disable `cuda` repo during `yum update`

scripts/run_commands
Updates the version of Miniforge in the Docker images. Also this version now uses Python 3.8 instead of Python 3.7. So should help us upgrade to the newer Python version.
xref: https://github.com/conda-forge/docker-images/pull/144
xref: https://github.com/conda-forge/miniforge/pull/50
cc @conda-forge/core
=> Use newer Miniforge (also update to Python 3.8)

scripts/run_commands
Fix a lingering Python 3.7 that was keeping us from updating to Python 3.8.
To cutdown on some duplication, just store the architecture beforehand and use that to build up the Miniforge URL. Also as we seem to always use `su-exec`, just inline to avoid an extra level of indirection.
=> Use Python 3.8 and simplify Miniforge selection

.github/workflows/ci.yaml, download-qemu-static.sh, linux-anvil-cos7-x86_64/Dockerfile
This should reduce some errors seen in emulation-based builds compared to our old pin from 2 years ago.
Additionally added the qemu-static binaries to our cos7-x68_64 image
Checklist
=> Update qemu-static to 5.1.0

.github/workflows/ci.yaml, README.md
Checklist
- Adds CUDA 11.2 support
- Updates docker tags used in `nvidia/cuda` which now include the [patch version](https://hub.docker.com/r/nvidia/cuda) for versions 11.0+
**NOTE:** This changes the use of `CUDA_VER` for CUDA `11.x`; open on suggestions as to whether the [documentation change](https://github.com/conda-forge/docker-images/pull/171/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R27-R29) is enough or there needs to be a new variable for the `nvidia/cuda` tag with major-minor-patch instead of using `CUDA_VER` as it may have unintended impacts.
cc @jakirkham
=> ENH Add CUDA 11.2 support and update nvidia/cuda docker tags

.github/workflows/ci.yaml, linux-anvil-ppc64le-cuda/Dockerfile
Checklist
I am adding PPC64LE images for CUDA 11.0 and 11.1, with cached `cudatoolkit` too. Since we are not packaging `cudatoolkit` for <10.2 (see https://github.com/conda-forge/cudatoolkit-feedstock/issues/12), those won't cache it.
=> PPC: add 11.0, 11.1, 11.2 + cached cudatoolkit pkg

linux-anvil-ppc64le-cuda/Dockerfile, linux-anvil-ppc64le-cuda/entrypoint_source
Checklist
PPC CUDA images were not exporting `$CUDA_HOME/bin` to `$PATH`, which prevents `cuda-gdb` from being found by our `nvcc` wrapper when it is trying to detect `$CUDA_HOME`.
=> PPC: add $CUDA_HOME/bin to $PATH

scripts/run_commands
This adds strict channel priority to the Docker images by default. Should resolve install issues like this one ( https://github.com/conda-forge/ctng-compilers-feedstock/issues/63 ).
On CI this is [overridden by this line]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/42a5c27a532bac0af40f329e64c9df36e3ebaaa4/recipe/run_conda_forge_build_setup_linux#L23-L27 ).
cc @beckermr
=> Enable strict channel priority in Docker images

.github/workflows/ci.yaml, linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-aarch64-cuda/entrypoint_source
Based off the existing ARM image and the PPC CUDA image, this adds a CUDA ARM image, which is needed for building CUDA ARM packages.
=> Add ARM image for CUDA

.github/workflows/ci.yaml
Not sure how this was configured to run cron jobs before, but this moves it into GH Actions. Runs [once weekly on Sunday at 0600 UTC]( https://crontab.guru/#0_6_*_*_SUN ), which  should hopefully be a lowish traffic time. Happy to change though if there are preferences
Note: It appears the images haven't been rebuilt in roughly 1 month.
=> Add weekly GH Action cron job

.github/workflows/ci.yaml, linux-anvil-cuda/Dockerfile
Checklist
The `nvidia/cuda` version `11.5` images aren't out quite yet, but this PR prepares the `conda-forge` Docker images for when they do come out :slightly_smiling_face:.
=> Add CUDA `11.5` variants to CI axis

linux-anvil-aarch64-cuda/entrypoint_source
Analogous to the change in PR ( https://github.com/conda-forge/docker-images/pull/181 ). Needed to discover CUDA Toolkit executables.
=> Add `$CUDA_HOME/bin` to `PATH` in CUDA ARM images

scripts/run_commands
* Drops an older `python` version pin (the current installer include `python=3.9`)
* Drops `setuptools` as it is unneeded
* Adds `pip` which is used in some places
Closes https://github.com/conda-forge/docker-images/issues/112
=> Update to Python 3.9 & drop unneeded packages

.github/workflows/ci.yaml
Fixes https://github.com/conda-forge/docker-images/issues/205
Previously only CentOS 8 images were available for CUDA 11.5. So we used those. However we would prefer to use CentOS 7 images where possible (and do for other CUDA versions on `x86_64`). Now that CentOS 7 images are available for CUDA 11.5, switch to those.
=> Use CentOS 7 for CUDA 11.5 images

linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile
Fixes https://github.com/conda-forge/docker-images/issues/208
Use CentOS Vault for `yum` to provide continued CentOS 8 support. Without this `yum` errors and the images won't build.
=> Fallback to CentOS Vault for CentOS 8 support

linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile
Fixes https://github.com/conda-forge/docker-images/issues/184
As this was copying the `entrypoint_source` files from the non-CUDA Docker images, it was only activating Conda and not adding CUDA executables to the `$PATH`.
=> Copy `entrypoint_source` next to `Dockerfile`

linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile
Makes a couple fixes to CentOS 8 Vault workaround in CUDA arch images:
* Disables the `cuda` repo in the `yum update` call
* Move `COPY` of `yum_clean_all` earlier
* Calls `yum_clean_all` in CentOS 8 workaround
=> Skip `cuda` repo update & use `yum_clean_all` in CUDA arch images

.github/workflows/ci.yaml
Adds a button on CI to enable kicking off a build of the image manually when needed.
Also `git` [fixed some CVEs recently]( https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/ ) in `2.39.1` ( https://github.com/conda-forge/git-feedstock/pull/127 ). The new package is in conda-forge, but we need a rebuild of the image to get it.
Finally rebuild to get `conda-build` repodata patch for `setuptools` ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/387 ).
=> Enable CI restart & rebuild for new `git`

linux-anvil-cuda/Dockerfile
=> Install qemu in linux-anvil-cuda

.github/workflows/keep-alive.yaml
Currently keep-alive job runs on any repo (including forks), which means it is pushing commits to those forks. This behavior is only needed on the main repo to ensure cron jobs continue to run (even if there hasn't been much activity on this repo). Forks don't have this need. So disable this job on forks.
=> Disable keep-alive job on forks

scripts/run_commands
To address some repodata issues seen in `defaults` affecting `mamba`, drop the `defaults` channel.
=> Drop `defaults` channel

.github/workflows/ci.yaml
As [noted at the previous conda-forge meeting]( https://github.com/conda-forge/conda-forge.github.io/blob/main/src/orga/minutes/2023-06-14.md ), some of these Docker images are going away. Please see [this notice]( https://gitlab.com/nvidia/container-images/cuda/-/issues/209#note_1452067531 ) and [the container support policy]( https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md )
Have rebuilt all of the images currently include in this repo with [this GHA job]( https://github.com/conda-forge/docker-images/actions/runs/5422331357 ) to ensure we have the latest build.
Some of the images just require a minor version bump, which is relatively straightforward.
With some of the `arm64` & `ppc64le` images, they are now no longer available with CentOS 8. So have …
=> Refresh CUDA Docker images based on EOL

linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-aarch64/Dockerfile, linux-anvil-comp7/Dockerfile, linux-anvil-cos7-x86_64/Dockerfile, linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile, linux-anvil-ppc64le/Dockerfile
These caches don't work usually because the version downloaded here is the newest while the feedstocks don't use the latest.
cc @h-vetinari
=> Remove caching of compilers

scripts/run_commands
The `run_commands` script was still pointing to an old version of Mambaforge (22.9). With https://github.com/conda-forge/miniforge/pull/277 now merged, it makes sense to standardize this across operating systems (macOS and Windows pull from latest Miniforge).
=> Update to Miniforge 23.3.1-0

.github/workflows/ci.yaml
=> Make sure the alma images have different names

.github/workflows/ci.yaml
The CUDA `aarch64le` & `ppc64le` CentOS 8 images are no longer available. So move them to UBI 8 based images, which are still around. This is what was done for the other CUDA images already ( https://github.com/conda-forge/docker-images/pull/237 ).
=> Move rest of CUDA arch images to UBI 8

download-qemu-static.sh, linux-anvil-alma/Dockerfile, linux-anvil-comp7/Dockerfile, linux-anvil-cos7-x86_64/Dockerfile
Checklist
closes gh-245
closes gh-228
The GitHub repo we pulled the binaries from before is not updated as mentioned by @h-vetinari in https://github.com/conda-forge/docker-images/issues/245#issue-2000753010 .
This now downloads the binaries from Fedora (or Debian).
=> Update qemu-user-static to version 8.0.4

download-qemu-static.sh
The Debian/Ubuntu builds are not necessarily available for long, apparently; this hinders scheduled rebuilds of our images.
Checklist
=> Switch to Fedora packges for qemu-user-static

.github/workflows/ci.yaml
Follows up on the discussion in issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5339 ) and [this announcement]( https://conda-forge.org/news/2024/03/06/dropping-cuda-112/ )
As the CUDA 11.0-11.3 images are deprecated and planned for removal as noted in [this comment]( https://gitlab.com/nvidia/container-images/cuda/-/issues/209#note_1641845842 ), this goes ahead and drops those
Further as CUDA 11.8 is becoming the new minimum in conda-forge ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5799 ), this drops all of the CUDA images before 11.8
For CUDA 12.x we use the normal conda-forge images
Thus should bring the CUDA image builds here down to one build per architecture. All of which are building CUDA 11.8 images. Simplifying the build matrix …
=> Drop old CUDA 11.x images

.github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/keep-alive.yaml
Checklist
xref https://github.com/conda-forge/infrastructure/pull/1
=> pin github actions; add dependabot

linux-anvil-alma/Dockerfile
The `devtoolset` compilers are no longer used (especially not in AlmaLinux builds where they have never been used). So drop this reference from this comment.
=> Drop `devtoolset` reference in AlmaLinux comment

.github/workflows/ci.yaml, README.md, linux-anvil-aarch64-cuda/Dockerfile, linux-anvil-aarch64-cuda/entrypoint_source, linux-anvil-cuda/Dockerfile, linux-anvil-ppc64le-cuda/Dockerfile, linux-anvil-ppc64le-cuda/entrypoint_source, scripts/fix_rpm
Reverts conda-forge/docker-images#272
Since this PR didn't have a proper review. I'm reverting this and will consider sending it again.
=> Revert "Cleanup and consolidate CUDA images"

download-qemu-static.sh
Recently the weekly cron jobs here [started failing]( https://github.com/conda-forge/docker-images/actions/runs/10757570540/job/29831758482 ). This appears related to in the QEMU preparation step
```
+ curl -sL https://kojipkgs.fedoraproject.org/packages/qemu/8.2.4/1.fc40/x86_64/qemu-user-static-aarch64-8.2.4-1.fc40.x86_64.rpm
+ bsdtar -xf- --strip-components=3 ./usr/bin/qemu-aarch64-static
bsdtar: Error opening archive: Unrecognized archive format
```
However when following the URL back, it appears upstream has [dropped the 8.2.4 binaries]( https://kojipkgs.fedoraproject.org/packages/qemu/8.2.4/ )
Also it appears there have been a few QEMU patch releases recently
To fix CI and update QEMU, this switches to the latest QEMU 8.2 patch release, which is 8.2.7
There is also a QEMU 9.0.0 and …
=> Bump QEMU to 8.2.7 (missing 8.2.4 binaries)

linux-anvil-cuda/Dockerfile
Previously `conda create --download-only` would still create an empty environment even when using `--download-only`. Not entirely sure when this got fixed.
However we know it did as `conda remove` now errors if an environment does not exist ( https://github.com/conda-forge/docker-images/pull/284#issuecomment-2387717756 ), which we are now seeing on CI ( https://github.com/conda-forge/docker-images/pull/284 ). The reason this only started happening now is `conda` version `24.9.0` was only just packaged on conda-forge earlier today ( https://github.com/conda-forge/conda-feedstock/pull/240 )
Given this, simply drop the unneeded `conda remove` line to fix the CI error
=> Drop `conda remove` for non-existent env

scripts/run_commands
Checklist
Noticed we were still on 23.3 and Python 3.10, which means the CI needs to bump it to Python 3.12 resulting in unnecessary churn.
=> Bump to Miniforge 24.7.1-2 and Python 3.12

.github/workflows/ci.yaml
The other two architectures are already on UBI 8
For https://github.com/conda-forge/conda-forge.github.io/issues/1941 / https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6283
Check out the available [tags](https://hub.docker.com/r/nvidia/cuda/tags?name=11.8.0); the required `-devel-{distro}` is only available for ppc if we use ubi8, so might as well use that distro for all architectures.
=> Provide `linux-anvil-cuda` on x64 with RHEL 8, consolidate image names, distinguish distro baseline in tag

download-qemu-static.sh
Fedora 41 has been released, and QEMU 9.x has seen both a minor and several patch releases.
I've also had a look at the QEMU issue tracker and didn't see anything that stood out in terms of open regressions.
CC @mbargull @isuruf
=> bump to QEMU 9.1.2

scripts/fix_rpm
With the switch to alma8 & alma9, some of our CDTs are now split across separate repos. In particular, we need `PowerTools` on alma8, resp. `CRB` on alma9 (which is essentially the same thing but got renamed). See for example https://github.com/conda-forge/cdt-builds/commit/e118347a73c4927c902aff7b928fa1dfafa65782
As an example, the following failed:
```
+ /usr/bin/sudo -n yum install -y wget m4 help2man patch gcc-gfortran gcc-c++ rsync sed findutils make file strace
AlmaLinux 9 - AppStream                          30 MB/s | 9.2 MB     00:00    
AlmaLinux 9 - BaseOS                            3.2 MB/s | 4.5 MB     00:01    
AlmaLinux 9 - Extras                             86 kB/s |  13 kB     00:00    
No match for argument: help2man
```
That package is …
=> Enable CRB repo on alma9, PowerTools on alma8

download-qemu-static.sh
The test suites in numpy and scipy show that QEMU 9 is massively slower than QEMU 8, and is causing the scipy test suite to hit the 6h timeout for roughly 4 out of 5 runs. The upgrade to v9 was made in the hopes of improving the testing situation in emulation, but this turned out to be a step back.
See also discussion in https://github.com/conda-forge/openblas-feedstock/issues/160
=> Back to QEMU 8.x
